.PHONY : all
all:
	cd avl_tree && make $@
	cd dynamic_array && make $@
	cd hash_map && make $@
	cd doubly_linked_list && make $@
	cd queue && make $@
	cd stack && make $@

.PHONY : run
run:
	cd avl_tree && make $@
	cd dynamic_array && make $@
	cd hash_map && make $@
	cd doubly_linked_list && make $@
	cd queue && make $@
	cd stack && make $@

.PHONY : clean
clean:
	cd avl_tree && make $@
	cd dynamic_array && make $@
	cd hash_map && make $@
	cd doubly_linked_list && make $@
	cd queue && make $@
	cd stack && make $@
